site_name: OPMATE Web Console
# docs_dir: v2.0/opme

theme:
  name: 'material'

nav:
  - INDEX: 'index.md'
  - '사용자': 'User.md'
  - '사용자그룹': 'UserGroup.md'
  - 'Sample': 'Sample.md'

markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true