site_name: OPMATE Web Console
# docs_dir: v2.0/opme
use_directory_urls: false

theme:
    name: material
    palette:
      scheme: slate
      primary: purple
      accent: deep purple
    font:
      text: Gowun Batang
      code: Nanum Gothic Coding
      # text: Noto Sans Korean
      # text: Stylish
    language: kr
#   name: cerulean
#   name: readthedocs
#   name: rtd-dropdown
#   name: 'material'
#   name: gitbook
#   name: bootstrap4
#   suppress_nextprev: false

nav:
  - '목차': 'index.md'
  - '로그인': 'Login.md'
  - '화면구성': 'Layout.md'
  - '사용자': 'User.md'
  - '사용자그룹': 'UserGroup.md'
  - '역할': 'Role.md'
  - '노드': 'Node.md'
  - 'Sample': 'Sample.md'
  - 'Popup':
      - '사용자': 'PopupUser.md'
      - '노드': 'PopupNode.md'

markdown_extensions:
  - attr_list
#   - def_list
#   - pymdownx.tasklist:
#       custom_checkbox: true