site_name: OPMATE Web Console
# docs_dir: v2.0/opme

theme:
  name: 'material'

nav:
  - INDEX: 'index.md'
  - 'User Guide': 'UserManual1.md'
  - '사용자': 'User.md'
  - '사용자1': 'User1.md'

markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true