site_name: OPMATE Web Console
# docs_dir: v2.0/opme
site_dir: ../../../opme/opmedocs
use_directory_urls: false
theme:
    name: material
    palette:
      scheme: defaulinfot
      primary: light blue
      accent: blue
    font:
      text: Noto Sans Korean
      code: Nanum Gothic Coding
      # text: Noto Sans Korean
      # text: Nanum Gothic
      # text: Gowun Batang
      # text: Stylish
    language: kr
#   name: cerulean
#   name: readthedocs
#   name: rtd-dropdown
#   name: 'material'
#   name: gitbook
#   name: bootstrap4
#   suppress_nextprev: false
extra:
    manual: 'opme'
nav:
  - '목차': 'index.md'
  - '개요': 'Overview.md'
  - '로그인': 'Login.md'
  - '주요화면':
      - '화면구성': 'Layout.md'
      - '사용자': 'User.md'
      - '사용자그룹': 'UserGroup.md'
      - '역할': 'Role.md'
      - '노드': 'Node.md'
      - '태스크': 'Task.md'
      - '태스크발행이력': 'Publist.md'
      - '태스크실행결과': 'Execution.md'
      - '단어사전': 'Dctnry.md'
      - '파일허브': 'FileHub.md'
      - '파일상세': 'File.md'
      - '엑세스키': 'AccKey.md'
      - '시스템속성': 'System.md'
  - 'Popup':
      - '사용자': 'PopupUser.md'
      - '사용자그룹': 'PopupUserGroup.md'
      - '노드': 'PopupNode.md'
      - '파일 업로드': 'PopupFileUpload.md'
      - '파일허브 조회': 'PopupFileHub.md'
      - '태스크 조회': 'PopupTask.md'
      - '태스크 선택': 'PopupTaskSelect.md'
      - '태스크 비교대상 선택': 'PopupTaskHistory.md'
      - '스케줄 추가': 'PopupSchedule.md'
      - '실행가능시간 추가': 'PopupRunnableTime.md'
      - '태스크 조건실행': 'PopupExecutionCondition.md'
      - '태스크 모의실행': 'PopupExecutionDryRun.md'
      - '태스크 실행상세': 'PopupExecutionDetail.md'
  - '정규표현식 정보': 'Regexp.md'

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
#   - def_list
#   - pymdownx.tasklist:
#       custom_checkbox: true

plugins:
  - macros