site_name: OPMATE Web Console
# docs_dir: v2.0/opme

theme:
  name: 'material'

nav:
  - INDEX: 'index.md'
  - '사용자': 'User.md'
  - 'Sample': 'Sample.md'
  - '사용자2': 'User2.md'

markdown_extensions:
  - attr_list
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true